Add GHA job to test against all iso-10303 schemas
lutaml/expressir pull request #175
Opened 2024-12-02 07:41 UTC by kwkwan

2024-12-02 09:35 UTC, ronaldtse requested changes

2024-12-02 09:35 UTC, ronaldtse commented on lib/tasks/test_schemas.rake
> +require "expressir"
We can just use the command line here to do it without a new Rake task:
(see https://github.com/metanorma/iso-10303/blob/main/.github/workflows/validate_express.yml)
```sh
bundle exec expressir validate schemas-srl.yml
bundle exec expressir validate schemas_module.yml
bundle exec expressir validate schemas_bom.yml
```

2024-12-02 09:36 UTC, ronaldtse commented on lib/tasks/test_schemas.rake
> +require "expressir"
This is also because not all `*.exp` files in the iso-10303 repository are valid (some are not meant to be tested).

2024-12-03 03:25 UTC, ronaldtse commented
Thank you @kwkwan !

For the schemas that are failing, can you please help create individual issues for them in Expressir (same type of failure goes in one issue)?

2024-12-03 03:25 UTC, merged

2024-12-03 03:43 UTC, kwkwan commented
@ronaldtse Ok. I will create individual issues for them.